export const detailCopy = {
  es: {
    share: 'Compartir propiedad',
    host: 'Propietario',
    hostVerified: 'Propietario verificado',
    bedroomsLabel: 'Habitaciones',
    bathroomsLabel: 'Baños',
    areaLabel: 'Superficie',
    ratingLabel: 'Valoración',
    locationTitle: 'Ubicación',
    category: 'Categoría',
    amenities: 'Lo que ofrece este lugar',
    noAmenities: 'El propietario todavía no ha detallado los servicios.',
    reserveVisit: 'Reservar visita',
    maps: 'Cómo llegar con Google Maps',
    noCharge: 'No se te cobrará nada todavía',
    contactHost: 'Contactar al propietario',
    verified: 'Verificada',
    longTerm: 'Largo plazo',
    shortTerm: 'Corta estancia',
    sale: 'Venta',
    perMonth: 'Por mes',
    perNight: 'Por noche',
    salePrice: 'Precio de venta',
  },
  fr: {
    share: 'Partager le logement',
    host: 'Hôte',
    hostVerified: 'Hôte vérifié',
    bedroomsLabel: 'Chambres',
    bathroomsLabel: 'Salles de bain',
    areaLabel: 'Surface',
    ratingLabel: 'Note',
    locationTitle: 'Emplacement',
    category: 'Catégorie',
    amenities: 'Ce que propose ce logement',
    noAmenities: 'L’hôte n’a pas encore détaillé les équipements.',
    reserveVisit: 'Réserver une visite',
    maps: 'Itinéraire avec Google Maps',
    noCharge: 'Aucun montant ne sera débité pour le moment',
    contactHost: 'Contacter l’hôte',
    verified: 'Vérifié',
    longTerm: 'Longue durée',
    shortTerm: 'Court séjour',
    sale: 'Vente',
    perMonth: 'Par mois',
    perNight: 'Par nuit',
    salePrice: 'Prix de vente',
  },
  en: {
    share: 'Share property',
    host: 'Host',
    hostVerified: 'Verified host',
    bedroomsLabel: 'Bedrooms',
    bathroomsLabel: 'Bathrooms',
    areaLabel: 'Area',
    ratingLabel: 'Rating',
    locationTitle: 'Location',
    category: 'Category',
    amenities: 'What this place offers',
    noAmenities: 'The host has not listed the amenities yet.',
    reserveVisit: 'Book a visit',
    maps: 'Directions with Google Maps',
    noCharge: 'You will not be charged yet',
    contactHost: 'Contact the host',
    verified: 'Verified',
    longTerm: 'Long term',
    shortTerm: 'Short stay',
    sale: 'Sale',
    perMonth: 'Per month',
    perNight: 'Per night',
    salePrice: 'Sale price',
  },
} as const;

export type DetailCopy = (typeof detailCopy)[keyof typeof detailCopy];
