import { useLocales } from 'expo-localization';
import { type PropsWithChildren, useCallback, useMemo, useState } from 'react';
import { setActiveLocale } from '@/lib/active-locale';
import { appStorage } from '@/lib/local-storage';
import { I18nContext, type I18nContextValue, type Locale } from '@/providers/i18n-context';

const copy = {
  es: {
    noPhotos: 'Sin fotografías',
    deleteChat: 'Eliminar chat', deleteChatTitle: '¿Eliminar este chat?', deleteChatBody: 'Se eliminará solo para ti: {name} seguirá viendo la conversación. Si vuelve a escribirte, el chat aparecerá de nuevo.', deleteChatError: 'No se pudo eliminar el chat. Inténtalo de nuevo.', deleteChatHint: 'Mantén pulsado para eliminar el chat',
    today: 'Hoy', yesterday: 'Ayer', messagePending: 'Enviando', messageFailed: 'No enviado. Toca para reintentar', scrollToLatest: 'Ir al último mensaje', viewPropertyLink: 'Ver la vivienda',
    legalVerified: 'Verificada', legalPending: 'En revisión', legalRestricted: 'Restringida', verifiedByCasaseg: 'Verificada por CasaSeg', reviewsLabel: 'reseñas', ownerBy: 'Propietario: {name}', whereToLive: '¿Dónde quieres vivir?', visitDayQuestion: '¿Qué día te viene bien?', visitTimeQuestion: '¿A qué hora?', visitSentTitle: 'Solicitud enviada', visitSentBody: '{owner} debe confirmar la visita del {date}.', backToProperty: 'Volver a la vivienda', pendingCount: 'Pendientes ({count})', confirmedVisits: 'Confirmadas', visitRequestLabel: 'Solicitud de visita', visitConfirmedLabel: 'Visita confirmada', yourHomes: 'Tus viviendas', publishHome: 'Publicar una vivienda', ownerMode: 'Modo propietario', manage: 'Gestionar', noVisitRequests: 'Sin solicitudes por ahora', entireHome: 'Vivienda entera en {location}',
    emailPlaceholder: 'correo@ejemplo.com', passwordPlaceholder: 'Introduce tu contraseña', newPasswordPlaceholder: 'Mínimo 8 caracteres', namePlaceholder: 'Nombre y apellidos',
    explore: 'Explorer', homeTab: 'Inicio', accessShort: 'Acceder', saved: 'Guardados', messages: 'Mensajes', profile: 'Perfil', profileSubtitle: 'Gestiona tu cuenta y accede a tus herramientas.', account: 'Tu cuenta', menu: 'Menú',
    greeting: 'Hola, {name}', guestGreeting: 'Encuentra tu próximo hogar', greetingSubtitle: 'Propiedades verificadas, cerca de ti.',
    searchTitle: 'Buscar', searchSubtitle: 'Buscar por ubicación, tipo…', list: 'Lista', map: 'Mapa',
    exploreEyebrow: 'EXPLORAR VIVIENDAS', featuredProperties: 'Propiedades destacadas', featuredDescription: 'Opciones verificadas con fotos, ubicación y detalles listos para comparar rápido.', recommended: 'Recomendadas', sortRating: 'Mejor valoradas', sortPriceAsc: 'Precio menor', sortPriceDesc: 'Precio mayor', sortNewest: 'Más recientes',
    properties: 'propiedades', sort: 'Ordenar', all: 'Todas', apartments: 'Apartamentos', apartmentsShort: 'Aptos.', houses: 'Casas', studios: 'Estudios',
    back: 'Volver', cancel: 'Cancelar', continue: 'Continuar', confirm: 'Confirmar', retry: 'Reintentar', loading: 'Cargando…',
    onboardingLoadingLabel: 'Cargando CasaSeg', onboardingPageStatus: 'Página {current} de {total}', onboardingNext: 'Siguiente', onboardingSkip: 'Saltar',
    onboardingDiscoverTitlePrimary: 'Encuentra tu hogar ideal', onboardingDiscoverTitleAccent: 'en Guinea Ecuatorial', onboardingDiscoverBody: 'Descubre las mejores propiedades en alquiler y venta. Apartamentos, villas y habitaciones en las mejores ubicaciones.',
    onboardingPropertyLoading: 'Buscando una vivienda disponible…', onboardingPropertyLoadError: 'No pudimos cargar la vivienda', onboardingTapToRetry: 'Toca para intentarlo de nuevo', onboardingPropertyAccessibility: '{title}, vivienda disponible en {location}',
    onboardingCommunityTitle: 'La confianza de\nnuestra comunidad', onboardingCommunitySubtitle: 'Únete a una red creciente de personas que buscan y publican viviendas en Guinea Ecuatorial.', onboardingActiveProperties: 'propiedades\nactivas', onboardingPublishingOwners: 'propietarios\npublicando', onboardingVerifiedMembers: 'miembros\nverificados', onboardingActiveUsers: '+{count} usuarios activos', onboardingCommunityLoading: 'Consultando la comunidad…', onboardingCommunityLoadError: 'No pudimos cargar la comunidad',
    onboardingGetStartedTitle: '¿Listo para empezar\na buscar?', onboardingGetStartedBody: 'Encuentra hoy tu vivienda ideal en Guinea Ecuatorial.', onboardingGetStartedCta: 'Empezar', onboardingHaveAccount: '¿Ya tienes una cuenta?', onboardingIllustrationAccessibility: 'Personas buscando vivienda frente a una casa',
    filtersTitle: 'Filtros', filtersSubtitle: 'Ajusta tu búsqueda antes de aplicarla.', reset: 'Restablecer', showResults: 'Mostrar {count} resultados', location: 'Ubicación', propertyName: 'Nombre', maxPrice: 'Precio máximo', availability: 'Disponibilidad', category: 'Categoría',
    loginTitle: 'Bienvenido a CasaSeg', loginSubtitle: 'Inicia sesión para guardar viviendas, conversar y gestionar contratos.', email: 'Correo', password: 'Contraseña', signIn: 'Iniciar sesión', signingIn: 'Entrando…', createAccount: 'Crear una cuenta', forgotPassword: 'He olvidado mi contraseña', rememberMe: 'Recordarme', showPassword: 'Mostrar contraseña', hidePassword: 'Ocultar contraseña', signInWithGoogle: 'Iniciar sesión con Google', signInWithApple: 'Iniciar sesión con Apple', termsAndConditions: 'Términos y condiciones', privacy: 'Privacidad', devMode: 'Modo de desarrollo', clientDemo: 'Entrar como cliente demo', ownerDemo: 'Entrar como propietario demo', adminDemo: 'Entrar como administrador demo',
    savedSubtitle: 'Tus viviendas favoritas, sincronizadas con tu cuenta.', noSaved: 'No tienes propiedades guardadas', saveHint: 'Usa el corazón en Explorer para guardar una vivienda.',
    messagesSubtitle: 'Conversaciones sobre propiedades, visitas y contratos.', connectionError: 'Error de conexión. Reintentar', noConversations: 'Aún no hay conversaciones', conversationHint: 'Contacta desde el detalle de una propiedad para empezar.', secureConversation: 'Conversación segura', firstMessage: 'Escribe el primer mensaje de esta conversación.', writeMessage: 'Escribe un mensaje…', sendMessage: 'Enviar mensaje',
    owner: 'Propietario', description: 'Descripción', amenities: 'Servicios', verifiedIdentity: 'Identidad verificada', requestVisit: 'Solicitar una visita', documentVerified: 'Documentación verificada', verificationPending: 'Verificación en curso', available: 'Disponible', occupied: 'Actualmente ocupada', contact: 'Contactar', editProperty: 'Editar propiedad', loginToContact: 'Iniciar sesión para contactar', openConversation: 'Abrir conversación', waitingList: 'Unirme a la lista de espera', notFound: 'Propiedad no encontrada.', beds: '{count} hab', baths: '{count} baños',
    mapSearch: 'Buscar en el mapa', mapCount: '{shown} de {total} en el mapa', viewList: 'Ver lista', myLocation: 'Mi ubicación', mapNativeOnly: 'Mapa disponible en iOS y Android', mapWebHint: 'Explora el mapa desde la app móvil de CasaSeg.', offline: 'Sin conexión · mostrando datos guardados',
    settings: 'Ajustes', settingsSubtitle: 'Personaliza el tema y el idioma de CasaSeg.', settingsSaveError: 'El ajuste se guardó en este dispositivo, pero no pudo sincronizarse.', theme: 'Tema', language: 'Idioma', light: 'Claro', dark: 'Oscuro', system: 'Sistema',
    notifications: 'Notificaciones', markRead: 'Marcar leídas', enablePush: 'Activar notificaciones push', pushEnabled: 'Push activado en este dispositivo', newBadge: 'Nuevo', saveProperty: 'Guardar propiedad', removeFavorite: 'Quitar de guardados', viewProperty: 'Ver {title}',
    noPropertyResults: 'No hay propiedades con estos filtros.', propertyLoadError: 'No pudimos cargar las propiedades. Toca para reintentar.',
    forgotTitle: 'Recuperar contraseña', forgotSubtitle: 'Te enviaremos un enlace seguro.', sendLink: 'Enviar enlace', checkEmail: 'Revisa tu correo para continuar.', backToLogin: 'Volver al acceso', resetTitle: 'Nueva contraseña', resetSubtitle: 'Crea una contraseña robusta para tu cuenta.', repeatPassword: 'Repite la contraseña', savePassword: 'Guardar contraseña', verifyTitle: 'Verifica tu cuenta', verifySubtitle: 'Introduce el código enviado a tu correo.', otpCode: 'Código OTP', verify: 'Verificar', otpEmailSent: 'Código enviado por correo', verifyInstructions: 'Introduce los 6 dígitos del mensaje de CasaSeg. El código solo puede utilizarse una vez.', otpSecurity: 'Nunca compartas este código. CasaSeg no te lo solicitará por teléfono o mensajería.', verifyingOtp: 'Verificando…', resendOtp: 'Reenviar código', resendingOtp: 'Reenviando…', resendIn: 'Reenviar en {count} s', otpResent: 'Hemos enviado un código nuevo. Revisa también la carpeta de spam.',
    visitTitle: 'Solicitar visita', visitSubtitle: 'Propón una fecha; el propietario deberá confirmarla.', dateTime: 'Fecha y hora', optionalMessage: 'Mensaje opcional', sending: 'Enviando…', sendRequest: 'Enviar solicitud',
    ownerPanel: 'Panel del propietario', ownerPanelSubtitle: 'Gestiona publicaciones, pagos y contratos desde el móvil.', myProperties: 'Mis propiedades', myPropertiesSubtitle: 'Publicaciones activas y borradores.', createProperty: 'Crear propiedad', requests: 'Solicitudes', payments: 'Pagos', contracts: 'Contratos', subscription: 'Suscripción', editPublication: 'Editar publicación',
    paymentsSubtitle: 'El servidor calcula el importe y confirma el pago mediante webhook.', paymentSecurity: 'CasaSeg nunca guarda datos de tarjeta ni confía en el deep link de éxito.', paySecure: 'Pagar con checkout seguro', checking: 'Consultando…', contractsSubtitle: 'Versiones inmutables, documentos privados y firma confirmada por el servidor.', version: 'Versión {count}', openPdf: 'Abrir PDF privado', signMfa: 'Firmar con MFA', subscriptionSubtitle: 'Mejora la visibilidad de tus propiedades desde un checkout seguro.', proPlan: 'Plan Profesional', proPlanDescription: 'Publicaciones destacadas y herramientas avanzadas para propietarios.', upgradePlan: 'Mejorar plan',
    adminWebNote: 'Las tareas administrativas avanzadas están disponibles preferentemente en el panel web.', signOut: 'Cerrar sesión',
    registerTitle: 'Crea tu cuenta', registerSubtitle: 'Accede a una experiencia segura para encontrar o publicar tu próximo hogar.', name: 'Nombre', client: 'Cliente', accountType: 'Elige tu experiencia', accountTypeHint: 'Podrás ampliar tu perfil más adelante.', clientRoleDescription: 'Encuentra, guarda y gestiona tus viviendas favoritas.', ownerRoleDescription: 'Publica propiedades y gestiona solicitudes de forma profesional.', passwordRequirement: 'Mínimo 8 caracteres para proteger tu cuenta.', creatingAccount: 'Creando cuenta…', secureRegistration: 'Registro protegido', registrationSecurity: 'Tus datos se cifran y se usan únicamente para proteger tu cuenta.', alreadyHaveAccount: '¿Ya tienes cuenta?',
    basicInfo: 'Información básica', priceMode: 'Precio y modalidad', features: 'Características', photos: 'Fotografías', preview: 'Vista previa', publication: 'Publicación', title: 'Título', price: 'Precio', serviceFee: 'Servicio', cleaningFee: 'Limpieza', taxes: 'Impuestos', securityDeposit: 'Depósito/fianza', priceBreakdown: 'Desglose del precio', estimatedTotal: 'Total inicial estimado', invalidFeeAmount: 'Introduce importes enteros de 0 FCFA o más.', bedrooms: 'Dormitorios', bathrooms: 'Baños', choosePhotos: 'Elegir y comprimir fotos', photo: 'Foto {count}', untitled: 'Sin título', pricePending: 'Precio pendiente', publishNotice: 'La publicación final requiere conexión. El servidor valida propietario, archivos y datos.', uploading: 'Subiendo {count}%', publishProperty: 'Publicar propiedad', saveChanges: 'Guardar cambios', saving: 'Guardando…',
    personalData: 'Datos personales', phone: 'Teléfono', address: 'Dirección', document: 'Documento', taxInfo: 'Información fiscal', payoutMethod: 'Método de cobro', plan: 'Plan', review: 'Revisión', confirmation: 'Confirmación', stepOf: 'Paso {current} de {total}', secureDocument: 'Los documentos sensibles se envían directamente al backend y no se guardan en el borrador local.', documentSent: 'Documento enviado', sendDocument: 'Enviar documento de forma segura',
    sendResetCode: 'Enviar código para crear contraseña', createPasswordForAccount: 'Crear una contraseña para esta cuenta', createAccountWithEmail: 'Crear una cuenta con este correo', propertyImageLabel: '{title}, imagen de la propiedad', pushEnableFailed: 'No se pudieron activar las notificaciones', pushEnableRetry: 'Inténtalo de nuevo cuando el servicio esté disponible.',
    pickLocationRequired: 'Selecciona el punto exacto de la vivienda para continuar.', pickLocationBeforePublish: 'Selecciona el punto exacto de la vivienda antes de publicar.', imagesProcessError: 'No se pudieron procesar las imágenes', publishError: 'No se pudo publicar', priceTypePerMonth: 'Por mes', priceTypePerNight: 'Por noche', priceTypeSale: 'Venta', photoControlsUp: 'Subir la foto {count}', photoControlsDown: 'Bajar la foto {count}', photoControlsRemove: 'Quitar la foto {count}',
    editPropertyNote: 'Los cambios se validan de nuevo en el servidor.', loadingListing: 'Cargando publicación…',
    locationDeniedTitle: 'Permiso no concedido', locationDeniedBody: 'Puedes seguir explorando el mapa y buscar por ubicación manualmente.', useMyLocation: 'Usar mi ubicación', useMyLocationBody: 'CasaSeg usará tu ubicación una sola vez para centrar el mapa y mostrar viviendas cercanas. No se guardará.', notNow: 'Ahora no', mapLoadError: 'No se pudieron cargar. Reintentar', passwordTooShort: 'La contraseña debe tener al menos 8 caracteres.', passwordsDontMatch: 'Las contraseñas no coinciden.', resetExpired: 'La solicitud expiró. Vuelve a pedir el código.', resetCodeSubtitle: 'Introduce el código que te enviamos y tu contraseña nueva.', verificationCode: 'Código de verificación', settingsSecurityNote: 'Tus ajustes se guardan de forma segura en tu cuenta.', errorScreenTitle: 'Algo se ha roto', errorScreenBody: 'La pantalla no se pudo mostrar. Puedes reintentarlo; si vuelve a pasar, cierra y abre la app.', pickLocationHint: 'Toca el mapa para marcar la vivienda. Puedes arrastrar el marcador para ajustar el punto.', pickLocationDone: 'Punto seleccionado para el mapa público', pickLocationPending: 'Selecciona un punto para continuar', coordinatesHint: 'Introduce las coordenadas exactas de la vivienda para mostrarla en el mapa.', latitude: 'Latitud', longitude: 'Longitud', latitudeLabel: 'Latitud de la vivienda', longitudeLabel: 'Longitud de la vivienda', coordinatesValid: 'Coordenadas válidas', coordinatesPending: 'Introduce ambas coordenadas para continuar',
    verifyingRole: 'Verificando rol', roleUnavailable: 'Rol no disponible', roleCheckFailed: 'No se pudo verificar tu responsabilidad', roleCheckFailedBody: 'Cierra sesión y vuelve a entrar. Si continúa, un administrador debe revisar el perfil asociado.', protectedAccount: 'Cuenta protegida', protectedAccountBody: 'Tus datos y conversaciones se gestionan con acceso seguro.', professionalSpace: 'ESPACIO PROFESIONAL', yourSearch: 'Tu búsqueda', savedActionDetail: 'Propiedades que quieres comparar', messagesActionDetail: 'Conversaciones con propietarios', notificationsActionDetail: 'Alertas, mensajes y actividad', settingsActionDetail: 'Tema, idioma y preferencias', quickManagement: 'Gestión rápida', myPropertiesActionDetail: 'Publicaciones y borradores', contractsActionDetail: 'Documentos y firmas', paymentsActionDetail: 'Cobros y operaciones',
    exploreProperties: 'Explorar propiedades', changeFilters: 'Cambiar filtros', changeSortOrder: 'Cambiar orden de propiedades', exploreLoadingTitle: 'Buscando propiedades', exploreLoadingBody: 'Estamos preparando las mejores opciones para ti.', exploreErrorTitle: 'No pudimos cargar las propiedades', exploreEmptyTitle: 'Sin resultados para estos filtros', loadingMoreProperties: 'Cargando más propiedades…', availableOnly: 'Disponibles', occupiedOnly: 'Ocupadas', closeGallery: 'Cerrar galería',
    savedEyebrow: 'TU COLECCIÓN', savedTitleFilled: 'Hogares que te inspiran', savedTitleEmpty: 'Tu selección personal', savedDetailFilled: 'Compara tus favoritos y elige con calma.', savedDetailEmpty: 'Guarda propiedades para encontrarlas rápidamente.', savedCount: '{count} guardadas', savedGuestTitle: 'Tus favoritos, siempre contigo', savedGuestBody: 'Inicia sesión para guardar propiedades, compararlas y sincronizarlas en todos tus dispositivos.', savedLoadingTitle: 'Preparando tu colección', savedLoadingBody: 'Estamos sincronizando las propiedades que has guardado.', savedErrorTitle: 'No pudimos cargar tus favoritos', savedErrorBody: 'Tu colección sigue segura. Comprueba la conexión e inténtalo de nuevo.',
    messagesEyebrow: 'CONVERSACIONES SEGURAS', inbox: 'Bandeja de entrada', inboxDetail: 'Consultas sobre propiedades, visitas y contratos.', unreadCount: '{count} sin leer', openConversationWith: 'Abrir conversación con {title}', messagesGuestTitle: 'Habla directamente con propietarios', messagesGuestBody: 'Inicia sesión para resolver dudas, coordinar visitas y conservar el historial de cada propiedad.', messagesLoadingTitle: 'Abriendo tus conversaciones', messagesLoadingBody: 'Estamos recuperando tus mensajes de forma segura.', messagesErrorTitle: 'No pudimos abrir la bandeja', messageSent: 'Enviado', messageDelivered: 'Entregado', messageRead: 'Leído', messageSendError: 'No se pudo enviar el mensaje. Inténtalo de nuevo.',
  },
  fr: {
    noPhotos: 'Aucune photo',
    deleteChat: 'Supprimer la discussion', deleteChatTitle: 'Supprimer cette discussion ?', deleteChatBody: 'Elle sera supprimée uniquement pour vous : {name} continuera de la voir. Si cette personne vous écrit à nouveau, la discussion réapparaîtra.', deleteChatError: 'Impossible de supprimer la discussion. Réessayez.', deleteChatHint: 'Appuyez longuement pour supprimer la discussion',
    today: 'Aujourd’hui', yesterday: 'Hier', messagePending: 'Envoi en cours', messageFailed: 'Non envoyé. Touchez pour réessayer', scrollToLatest: 'Aller au dernier message', viewPropertyLink: 'Voir le logement',
    legalVerified: 'Vérifiée', legalPending: 'En cours de vérification', legalRestricted: 'Restreinte', verifiedByCasaseg: 'Vérifiée par CasaSeg', reviewsLabel: 'avis', ownerBy: 'Propriétaire : {name}', whereToLive: 'Où voulez-vous vivre ?', visitDayQuestion: 'Quel jour vous convient ?', visitTimeQuestion: 'À quelle heure ?', visitSentTitle: 'Demande envoyée', visitSentBody: '{owner} doit confirmer la visite du {date}.', backToProperty: 'Retour au logement', pendingCount: 'En attente ({count})', confirmedVisits: 'Confirmées', visitRequestLabel: 'Demande de visite', visitConfirmedLabel: 'Visite confirmée', yourHomes: 'Vos logements', publishHome: 'Publier un logement', ownerMode: 'Mode propriétaire', manage: 'Gérer', noVisitRequests: 'Aucune demande pour le moment', entireHome: 'Logement entier à {location}',
    emailPlaceholder: 'nom@exemple.com', passwordPlaceholder: 'Saisissez votre mot de passe', newPasswordPlaceholder: '8 caractères minimum', namePlaceholder: 'Nom et prénom',
    explore: 'Explorer', homeTab: 'Accueil', accessShort: 'Accéder', saved: 'Favoris', messages: 'Messages', profile: 'Profil', profileSubtitle: 'Gérez votre compte et accédez à vos outils.', account: 'Votre compte', menu: 'Menu',
    greeting: 'Bonjour, {name}', guestGreeting: 'Trouvez votre prochain logement', greetingSubtitle: 'Des biens vérifiés, près de chez vous.',
    searchTitle: 'Rechercher', searchSubtitle: 'Lieu, type de bien…', list: 'Liste', map: 'Carte',
    exploreEyebrow: 'EXPLORER LES LOGEMENTS', featuredProperties: 'Biens en vedette', featuredDescription: 'Des options vérifiées avec photos, emplacement et détails pour comparer rapidement.', recommended: 'Recommandées', sortRating: 'Mieux notées', sortPriceAsc: 'Prix croissant', sortPriceDesc: 'Prix décroissant', sortNewest: 'Plus récentes',
    properties: 'propriétés', sort: 'Trier', all: 'Tous', apartments: 'Appartements', apartmentsShort: 'Appart.', houses: 'Maisons', studios: 'Studios',
    back: 'Retour', cancel: 'Annuler', continue: 'Continuer', confirm: 'Confirmer', retry: 'Réessayer', loading: 'Chargement…',
    onboardingLoadingLabel: 'Chargement de CasaSeg', onboardingPageStatus: 'Page {current} sur {total}', onboardingNext: 'Suivant', onboardingSkip: 'Passer',
    onboardingDiscoverTitlePrimary: 'Trouvez le logement idéal', onboardingDiscoverTitleAccent: 'en Guinée équatoriale', onboardingDiscoverBody: 'Découvrez les meilleurs biens à louer et à vendre : appartements, villas et chambres dans les meilleurs quartiers.',
    onboardingPropertyLoading: 'Recherche d’un logement disponible…', onboardingPropertyLoadError: 'Impossible de charger le logement', onboardingTapToRetry: 'Touchez pour réessayer', onboardingPropertyAccessibility: '{title}, logement disponible à {location}',
    onboardingCommunityTitle: 'La confiance de\nnotre communauté', onboardingCommunitySubtitle: 'Rejoignez un réseau grandissant de personnes qui cherchent et publient des logements en Guinée équatoriale.', onboardingActiveProperties: 'biens\nactifs', onboardingPublishingOwners: 'propriétaires\nactifs', onboardingVerifiedMembers: 'membres\nvérifiés', onboardingActiveUsers: '+{count} utilisateurs actifs', onboardingCommunityLoading: 'Consultation de la communauté…', onboardingCommunityLoadError: 'Impossible de charger la communauté',
    onboardingGetStartedTitle: 'Prêt à commencer\nvotre recherche ?', onboardingGetStartedBody: 'Trouvez dès aujourd’hui votre logement idéal en Guinée équatoriale.', onboardingGetStartedCta: 'Commencer', onboardingHaveAccount: 'Vous avez déjà un compte ?', onboardingIllustrationAccessibility: 'Des personnes cherchent un logement devant une maison',
    filtersTitle: 'Filtres', filtersSubtitle: 'Ajustez votre recherche avant de l’appliquer.', reset: 'Réinitialiser', showResults: 'Afficher {count} résultats', location: 'Lieu', propertyName: 'Nom', maxPrice: 'Prix maximum', availability: 'Disponibilité', category: 'Catégorie',
    loginTitle: 'Bienvenue sur CasaSeg', loginSubtitle: 'Connectez-vous pour enregistrer des logements, discuter et gérer vos contrats.', email: 'E-mail', password: 'Mot de passe', signIn: 'Se connecter', signingIn: 'Connexion…', createAccount: 'Créer un compte', forgotPassword: 'Mot de passe oublié', rememberMe: 'Se souvenir de moi', showPassword: 'Afficher le mot de passe', hidePassword: 'Masquer le mot de passe', signInWithGoogle: 'Se connecter avec Google', signInWithApple: 'Se connecter avec Apple', termsAndConditions: 'Conditions générales', privacy: 'Confidentialité', devMode: 'Mode développement', clientDemo: 'Entrer comme client démo', ownerDemo: 'Entrer comme propriétaire démo', adminDemo: 'Entrer comme administrateur démo',
    savedSubtitle: 'Vos logements favoris, synchronisés avec votre compte.', noSaved: 'Aucun logement enregistré', saveHint: 'Utilisez le cœur dans Explorer pour enregistrer un logement.',
    messagesSubtitle: 'Conversations sur les logements, visites et contrats.', connectionError: 'Erreur de connexion. Réessayer', noConversations: 'Aucune conversation', conversationHint: 'Contactez un propriétaire depuis la fiche du logement.', secureConversation: 'Conversation sécurisée', firstMessage: 'Écrivez le premier message.', writeMessage: 'Écrire un message…', sendMessage: 'Envoyer le message',
    owner: 'Propriétaire', description: 'Description', amenities: 'Services', verifiedIdentity: 'Identité vérifiée', requestVisit: 'Demander une visite', documentVerified: 'Documents vérifiés', verificationPending: 'Vérification en cours', available: 'Disponible', occupied: 'Actuellement occupé', contact: 'Contacter', editProperty: 'Modifier le bien', loginToContact: 'Se connecter pour contacter', openConversation: 'Ouvrir la conversation', waitingList: 'Rejoindre la liste d’attente', notFound: 'Bien introuvable.', beds: '{count} ch.', baths: '{count} salles de bain',
    mapSearch: 'Rechercher sur la carte', mapCount: '{shown} sur {total} sur la carte', viewList: 'Voir la liste', myLocation: 'Ma position', mapNativeOnly: 'Carte disponible sur iOS et Android', mapWebHint: 'Explorez la carte dans l’application mobile CasaSeg.', offline: 'Hors ligne · données enregistrées affichées',
    settings: 'Réglages', settingsSubtitle: 'Personnalisez le thème et la langue de CasaSeg.', settingsSaveError: 'Le réglage est enregistré sur cet appareil, mais la synchronisation a échoué.', theme: 'Thème', language: 'Langue', light: 'Clair', dark: 'Sombre', system: 'Système',
    notifications: 'Notifications', markRead: 'Tout marquer comme lu', enablePush: 'Activer les notifications push', pushEnabled: 'Push activé sur cet appareil', newBadge: 'Nouveau', saveProperty: 'Enregistrer le bien', removeFavorite: 'Retirer des favoris', viewProperty: 'Voir {title}',
    noPropertyResults: 'Aucun bien ne correspond à ces filtres.', propertyLoadError: 'Impossible de charger les biens. Touchez pour réessayer.',
    forgotTitle: 'Réinitialiser le mot de passe', forgotSubtitle: 'Nous vous enverrons un lien sécurisé.', sendLink: 'Envoyer le lien', checkEmail: 'Consultez votre e-mail pour continuer.', backToLogin: 'Retour à la connexion', resetTitle: 'Nouveau mot de passe', resetSubtitle: 'Créez un mot de passe robuste.', repeatPassword: 'Répéter le mot de passe', savePassword: 'Enregistrer le mot de passe', verifyTitle: 'Vérifiez votre compte', verifySubtitle: 'Saisissez le code reçu par e-mail.', otpCode: 'Code OTP', verify: 'Vérifier', otpEmailSent: 'Code envoyé par e-mail', verifyInstructions: 'Saisissez les 6 chiffres du message CasaSeg. Le code ne peut être utilisé qu’une fois.', otpSecurity: 'Ne partagez jamais ce code. CasaSeg ne vous le demandera pas par téléphone ou messagerie.', verifyingOtp: 'Vérification…', resendOtp: 'Renvoyer le code', resendingOtp: 'Renvoi…', resendIn: 'Renvoyer dans {count} s', otpResent: 'Un nouveau code a été envoyé. Vérifiez également le dossier indésirable.',
    visitTitle: 'Demander une visite', visitSubtitle: 'Proposez une date que le propriétaire devra confirmer.', dateTime: 'Date et heure', optionalMessage: 'Message facultatif', sending: 'Envoi…', sendRequest: 'Envoyer la demande',
    ownerPanel: 'Espace propriétaire', ownerPanelSubtitle: 'Gérez vos annonces, paiements et contrats sur mobile.', myProperties: 'Mes biens', myPropertiesSubtitle: 'Annonces actives et brouillons.', createProperty: 'Créer un bien', requests: 'Demandes', payments: 'Paiements', contracts: 'Contrats', subscription: 'Abonnement', editPublication: 'Modifier l’annonce',
    paymentsSubtitle: 'Le serveur calcule le montant et confirme le paiement par webhook.', paymentSecurity: 'CasaSeg ne stocke jamais les cartes et ne se fie pas au lien de retour.', paySecure: 'Payer par checkout sécurisé', checking: 'Vérification…', contractsSubtitle: 'Versions immuables, documents privés et signature confirmée par le serveur.', version: 'Version {count}', openPdf: 'Ouvrir le PDF privé', signMfa: 'Signer avec MFA', subscriptionSubtitle: 'Améliorez la visibilité de vos biens via un checkout sécurisé.', proPlan: 'Plan Professionnel', proPlanDescription: 'Annonces mises en avant et outils avancés pour propriétaires.', upgradePlan: 'Améliorer le plan',
    adminWebNote: 'Les tâches administratives avancées sont disponibles de préférence sur le web.', signOut: 'Se déconnecter',
    registerTitle: 'Créez votre compte', registerSubtitle: 'Accédez à une expérience sécurisée pour trouver ou publier votre prochain logement.', name: 'Nom', client: 'Client', accountType: 'Choisissez votre expérience', accountTypeHint: 'Vous pourrez enrichir votre profil plus tard.', clientRoleDescription: 'Trouvez, enregistrez et gérez vos logements favoris.', ownerRoleDescription: 'Publiez des biens et gérez les demandes professionnellement.', passwordRequirement: '8 caractères minimum pour protéger votre compte.', creatingAccount: 'Création du compte…', secureRegistration: 'Inscription protégée', registrationSecurity: 'Vos données sont chiffrées et utilisées uniquement pour protéger votre compte.', alreadyHaveAccount: 'Vous avez déjà un compte ?',
    basicInfo: 'Informations de base', priceMode: 'Prix et modalité', features: 'Caractéristiques', photos: 'Photos', preview: 'Aperçu', publication: 'Publication', title: 'Titre', price: 'Prix', serviceFee: 'Service', cleaningFee: 'Ménage', taxes: 'Taxes', securityDeposit: 'Dépôt de garantie', priceBreakdown: 'Détail du prix', estimatedTotal: 'Total initial estimé', invalidFeeAmount: 'Saisissez des montants entiers de 0 FCFA ou plus.', bedrooms: 'Chambres', bathrooms: 'Salles de bain', choosePhotos: 'Choisir et compresser les photos', photo: 'Photo {count}', untitled: 'Sans titre', pricePending: 'Prix en attente', publishNotice: 'La publication finale exige une connexion. Le serveur valide le propriétaire, les fichiers et les données.', uploading: 'Envoi {count}%', publishProperty: 'Publier le bien', saveChanges: 'Enregistrer', saving: 'Enregistrement…',
    personalData: 'Données personnelles', phone: 'Téléphone', address: 'Adresse', document: 'Document', taxInfo: 'Informations fiscales', payoutMethod: 'Mode de paiement', plan: 'Plan', review: 'Révision', confirmation: 'Confirmation', stepOf: 'Étape {current} sur {total}', secureDocument: 'Les documents sensibles sont envoyés directement au serveur et ne sont pas conservés dans le brouillon.', documentSent: 'Document envoyé', sendDocument: 'Envoyer le document en sécurité',
    sendResetCode: 'Envoyer un code pour créer un mot de passe', createPasswordForAccount: 'Créer un mot de passe pour ce compte', createAccountWithEmail: 'Créer un compte avec cet e-mail', propertyImageLabel: '{title}, photo du logement', pushEnableFailed: 'Impossible d’activer les notifications', pushEnableRetry: 'Réessayez lorsque le service sera disponible.',
    pickLocationRequired: 'Sélectionnez l’emplacement exact du logement pour continuer.', pickLocationBeforePublish: 'Sélectionnez l’emplacement exact du logement avant de publier.', imagesProcessError: 'Impossible de traiter les images', publishError: 'La publication a échoué', priceTypePerMonth: 'Par mois', priceTypePerNight: 'Par nuit', priceTypeSale: 'Vente', photoControlsUp: 'Monter la photo {count}', photoControlsDown: 'Descendre la photo {count}', photoControlsRemove: 'Retirer la photo {count}',
    editPropertyNote: 'Les modifications sont à nouveau validées par le serveur.', loadingListing: 'Chargement de l’annonce…',
    locationDeniedTitle: 'Autorisation refusée', locationDeniedBody: 'Vous pouvez continuer à explorer la carte et rechercher un lieu manuellement.', useMyLocation: 'Utiliser ma position', useMyLocationBody: 'CasaSeg utilisera votre position une seule fois pour centrer la carte et afficher les logements proches. Elle ne sera pas enregistrée.', notNow: 'Pas maintenant', mapLoadError: 'Chargement impossible. Réessayer', passwordTooShort: 'Le mot de passe doit contenir au moins 8 caractères.', passwordsDontMatch: 'Les mots de passe ne correspondent pas.', resetExpired: 'La demande a expiré. Demandez un nouveau code.', resetCodeSubtitle: 'Saisissez le code reçu et votre nouveau mot de passe.', verificationCode: 'Code de vérification', settingsSecurityNote: 'Vos réglages sont enregistrés en toute sécurité dans votre compte.', errorScreenTitle: 'Un problème est survenu', errorScreenBody: 'L’écran n’a pas pu s’afficher. Réessayez ; si cela se reproduit, fermez puis rouvrez l’application.', pickLocationHint: 'Touchez la carte pour placer le logement. Vous pouvez faire glisser le repère pour ajuster le point.', pickLocationDone: 'Point sélectionné pour la carte publique', pickLocationPending: 'Sélectionnez un point pour continuer', coordinatesHint: 'Saisissez les coordonnées exactes du logement pour l’afficher sur la carte.', latitude: 'Latitude', longitude: 'Longitude', latitudeLabel: 'Latitude du logement', longitudeLabel: 'Longitude du logement', coordinatesValid: 'Coordonnées valides', coordinatesPending: 'Saisissez les deux coordonnées pour continuer',
    verifyingRole: 'Vérification du rôle', roleUnavailable: 'Rôle indisponible', roleCheckFailed: 'Impossible de vérifier votre rôle', roleCheckFailedBody: 'Déconnectez-vous puis reconnectez-vous. Si le problème persiste, un administrateur doit vérifier le profil associé.', protectedAccount: 'Compte protégé', protectedAccountBody: 'Vos données et conversations sont gérées avec un accès sécurisé.', professionalSpace: 'ESPACE PROFESSIONNEL', yourSearch: 'Votre recherche', savedActionDetail: 'Les logements que vous voulez comparer', messagesActionDetail: 'Conversations avec les propriétaires', notificationsActionDetail: 'Alertes, messages et activité', settingsActionDetail: 'Thème, langue et préférences', quickManagement: 'Gestion rapide', myPropertiesActionDetail: 'Annonces et brouillons', contractsActionDetail: 'Documents et signatures', paymentsActionDetail: 'Encaissements et opérations',
    exploreProperties: 'Explorer les logements', changeFilters: 'Modifier les filtres', changeSortOrder: 'Changer l’ordre des logements', exploreLoadingTitle: 'Recherche de logements', exploreLoadingBody: 'Nous préparons les meilleures options pour vous.', exploreErrorTitle: 'Impossible de charger les logements', exploreEmptyTitle: 'Aucun résultat pour ces filtres', loadingMoreProperties: 'Chargement d’autres logements…', availableOnly: 'Disponibles', occupiedOnly: 'Occupés', closeGallery: 'Fermer la galerie',
    savedEyebrow: 'VOTRE COLLECTION', savedTitleFilled: 'Des logements qui vous inspirent', savedTitleEmpty: 'Votre sélection personnelle', savedDetailFilled: 'Comparez vos favoris et choisissez sereinement.', savedDetailEmpty: 'Enregistrez des logements pour les retrouver rapidement.', savedCount: '{count} enregistrés', savedGuestTitle: 'Vos favoris, toujours avec vous', savedGuestBody: 'Connectez-vous pour enregistrer des logements, les comparer et les synchroniser sur tous vos appareils.', savedLoadingTitle: 'Préparation de votre collection', savedLoadingBody: 'Nous synchronisons les logements que vous avez enregistrés.', savedErrorTitle: 'Impossible de charger vos favoris', savedErrorBody: 'Votre collection est en sécurité. Vérifiez la connexion et réessayez.',
    messagesEyebrow: 'CONVERSATIONS SÉCURISÉES', inbox: 'Boîte de réception', inboxDetail: 'Questions sur les logements, visites et contrats.', unreadCount: '{count} non lus', openConversationWith: 'Ouvrir la conversation avec {title}', messagesGuestTitle: 'Parlez directement aux propriétaires', messagesGuestBody: 'Connectez-vous pour poser vos questions, organiser des visites et garder l’historique de chaque logement.', messagesLoadingTitle: 'Ouverture de vos conversations', messagesLoadingBody: 'Nous récupérons vos messages en toute sécurité.', messagesErrorTitle: 'Impossible d’ouvrir la boîte de réception', messageSent: 'Envoyé', messageDelivered: 'Distribué', messageRead: 'Lu', messageSendError: 'Le message n’a pas pu être envoyé. Réessayez.',
  },
  en: {
    noPhotos: 'No photos yet',
    deleteChat: 'Delete chat', deleteChatTitle: 'Delete this chat?', deleteChatBody: 'It will be deleted only for you: {name} will still see the conversation. If they write to you again, the chat will reappear.', deleteChatError: 'The chat could not be deleted. Try again.', deleteChatHint: 'Long press to delete the chat',
    today: 'Today', yesterday: 'Yesterday', messagePending: 'Sending', messageFailed: 'Not sent. Tap to retry', scrollToLatest: 'Go to latest message', viewPropertyLink: 'View the home',
    legalVerified: 'Verified', legalPending: 'Under review', legalRestricted: 'Restricted', verifiedByCasaseg: 'Verified by CasaSeg', reviewsLabel: 'reviews', ownerBy: 'Owner: {name}', whereToLive: 'Where do you want to live?', visitDayQuestion: 'Which day works for you?', visitTimeQuestion: 'What time?', visitSentTitle: 'Request sent', visitSentBody: '{owner} needs to confirm the visit on {date}.', backToProperty: 'Back to the property', pendingCount: 'Pending ({count})', confirmedVisits: 'Confirmed', visitRequestLabel: 'Visit request', visitConfirmedLabel: 'Visit confirmed', yourHomes: 'Your homes', publishHome: 'Publish a home', ownerMode: 'Owner mode', manage: 'Manage', noVisitRequests: 'No requests yet', entireHome: 'Entire home in {location}',
    emailPlaceholder: 'name@example.com', passwordPlaceholder: 'Enter your password', newPasswordPlaceholder: 'At least 8 characters', namePlaceholder: 'Full name',
    explore: 'Explore', homeTab: 'Home', accessShort: 'Sign in', saved: 'Saved', messages: 'Messages', profile: 'Profile', profileSubtitle: 'Manage your account and access your tools.', account: 'Your account', menu: 'Menu',
    greeting: 'Hello, {name}', guestGreeting: 'Find your next home', greetingSubtitle: 'Verified properties, close to you.',
    searchTitle: 'Search', searchSubtitle: 'Location, property type…', list: 'List', map: 'Map',
    exploreEyebrow: 'EXPLORE HOMES', featuredProperties: 'Featured properties', featuredDescription: 'Verified options with photos, locations, and details ready for quick comparison.', recommended: 'Recommended', sortRating: 'Top rated', sortPriceAsc: 'Lowest price', sortPriceDesc: 'Highest price', sortNewest: 'Newest',
    properties: 'properties', sort: 'Sort', all: 'All', apartments: 'Apartments', apartmentsShort: 'Apts.', houses: 'Houses', studios: 'Studios',
    back: 'Back', cancel: 'Cancel', continue: 'Continue', confirm: 'Confirm', retry: 'Retry', loading: 'Loading…',
    onboardingLoadingLabel: 'Loading CasaSeg', onboardingPageStatus: 'Page {current} of {total}', onboardingNext: 'Next', onboardingSkip: 'Skip',
    onboardingDiscoverTitlePrimary: 'Find your perfect home', onboardingDiscoverTitleAccent: 'in Equatorial Guinea', onboardingDiscoverBody: 'Discover the best properties for rent and sale. Apartments, villas, and rooms in the best locations.',
    onboardingPropertyLoading: 'Finding an available home…', onboardingPropertyLoadError: 'We could not load the property', onboardingTapToRetry: 'Tap to try again', onboardingPropertyAccessibility: '{title}, home available in {location}',
    onboardingCommunityTitle: 'Trusted by the\nCommunity', onboardingCommunitySubtitle: 'Join a growing network of property seekers and owners in Equatorial Guinea.', onboardingActiveProperties: 'active\nproperties', onboardingPublishingOwners: 'owners\npublishing', onboardingVerifiedMembers: 'verified\nmembers', onboardingActiveUsers: '+{count} active users', onboardingCommunityLoading: 'Checking the community…', onboardingCommunityLoadError: 'We could not load the community',
    onboardingGetStartedTitle: 'Ready to start\nsearching?', onboardingGetStartedBody: 'Find your perfect rental property in Equatorial Guinea today.', onboardingGetStartedCta: 'Get Started', onboardingHaveAccount: 'Already have an account?', onboardingIllustrationAccessibility: 'People searching for a home in front of a house',
    filtersTitle: 'Filters', filtersSubtitle: 'Adjust your search before applying it.', reset: 'Reset', showResults: 'Show {count} results', location: 'Location', propertyName: 'Name', maxPrice: 'Maximum price', availability: 'Availability', category: 'Category',
    loginTitle: 'Welcome to CasaSeg', loginSubtitle: 'Sign in to save homes, chat, and manage contracts.', email: 'Email', password: 'Password', signIn: 'Sign in', signingIn: 'Signing in…', createAccount: 'Create an account', forgotPassword: 'I forgot my password', rememberMe: 'Remember me', showPassword: 'Show password', hidePassword: 'Hide password', signInWithGoogle: 'Sign in with Google', signInWithApple: 'Sign in with Apple', termsAndConditions: 'Terms and conditions', privacy: 'Privacy', devMode: 'Development mode', clientDemo: 'Enter as demo client', ownerDemo: 'Enter as demo owner', adminDemo: 'Enter as demo administrator',
    savedSubtitle: 'Your favorite homes, synced with your account.', noSaved: 'No saved properties', saveHint: 'Use the heart in Explore to save a home.',
    messagesSubtitle: 'Conversations about properties, visits, and contracts.', connectionError: 'Connection error. Retry', noConversations: 'No conversations yet', conversationHint: 'Contact a property from its detail screen to begin.', secureConversation: 'Secure conversation', firstMessage: 'Write the first message in this conversation.', writeMessage: 'Write a message…', sendMessage: 'Send message',
    owner: 'Owner', description: 'Description', amenities: 'Amenities', verifiedIdentity: 'Verified identity', requestVisit: 'Request a visit', documentVerified: 'Documents verified', verificationPending: 'Verification in progress', available: 'Available', occupied: 'Currently occupied', contact: 'Contact', editProperty: 'Edit property', loginToContact: 'Sign in to contact', openConversation: 'Open conversation', waitingList: 'Join the waiting list', notFound: 'Property not found.', beds: '{count} beds', baths: '{count} baths',
    mapSearch: 'Search on map', mapCount: '{shown} of {total} on the map', viewList: 'View list', myLocation: 'My location', mapNativeOnly: 'Map available on iOS and Android', mapWebHint: 'Explore the map in the CasaSeg mobile app.', offline: 'Offline · showing saved data',
    settings: 'Settings', settingsSubtitle: 'Customize CasaSeg theme and language.', settingsSaveError: 'The setting was saved on this device but could not be synchronized.', theme: 'Theme', language: 'Language', light: 'Light', dark: 'Dark', system: 'System',
    notifications: 'Notifications', markRead: 'Mark as read', enablePush: 'Enable push notifications', pushEnabled: 'Push enabled on this device', newBadge: 'New', saveProperty: 'Save property', removeFavorite: 'Remove from saved', viewProperty: 'View {title}',
    noPropertyResults: 'No properties match these filters.', propertyLoadError: 'We could not load properties. Tap to retry.',
    forgotTitle: 'Reset password', forgotSubtitle: 'We will send you a secure link.', sendLink: 'Send link', checkEmail: 'Check your email to continue.', backToLogin: 'Back to sign in', resetTitle: 'New password', resetSubtitle: 'Create a strong password for your account.', repeatPassword: 'Repeat password', savePassword: 'Save password', verifyTitle: 'Verify your account', verifySubtitle: 'Enter the code sent to your email.', otpCode: 'OTP code', verify: 'Verify', otpEmailSent: 'Code sent by email', verifyInstructions: 'Enter the 6 digits from the CasaSeg message. The code can only be used once.', otpSecurity: 'Never share this code. CasaSeg will not request it by phone or messaging.', verifyingOtp: 'Verifying…', resendOtp: 'Resend code', resendingOtp: 'Resending…', resendIn: 'Resend in {count} s', otpResent: 'A new code has been sent. Please also check your spam folder.',
    visitTitle: 'Request a visit', visitSubtitle: 'Propose a date for the owner to confirm.', dateTime: 'Date and time', optionalMessage: 'Optional message', sending: 'Sending…', sendRequest: 'Send request',
    ownerPanel: 'Owner dashboard', ownerPanelSubtitle: 'Manage listings, payments, and contracts on mobile.', myProperties: 'My properties', myPropertiesSubtitle: 'Active listings and drafts.', createProperty: 'Create property', requests: 'Requests', payments: 'Payments', contracts: 'Contracts', subscription: 'Subscription', editPublication: 'Edit listing',
    paymentsSubtitle: 'The server calculates the amount and confirms payment through a webhook.', paymentSecurity: 'CasaSeg never stores card data or trusts a success deep link.', paySecure: 'Pay with secure checkout', checking: 'Checking…', contractsSubtitle: 'Immutable versions, private documents, and server-confirmed signatures.', version: 'Version {count}', openPdf: 'Open private PDF', signMfa: 'Sign with MFA', subscriptionSubtitle: 'Improve property visibility through a secure checkout.', proPlan: 'Professional Plan', proPlanDescription: 'Featured listings and advanced owner tools.', upgradePlan: 'Upgrade plan',
    adminWebNote: 'Advanced administration tasks are preferably available on the web dashboard.', signOut: 'Sign out',
    registerTitle: 'Create your account', registerSubtitle: 'Enjoy a secure experience to find or publish your next home.', name: 'Name', client: 'Client', accountType: 'Choose your experience', accountTypeHint: 'You can expand your profile later.', clientRoleDescription: 'Find, save, and manage your favorite homes.', ownerRoleDescription: 'Publish properties and manage requests professionally.', passwordRequirement: 'Use at least 8 characters to protect your account.', creatingAccount: 'Creating account…', secureRegistration: 'Protected registration', registrationSecurity: 'Your data is encrypted and used only to protect your account.', alreadyHaveAccount: 'Already have an account?',
    basicInfo: 'Basic information', priceMode: 'Price and mode', features: 'Features', photos: 'Photos', preview: 'Preview', publication: 'Publication', title: 'Title', price: 'Price', serviceFee: 'Service', cleaningFee: 'Cleaning', taxes: 'Taxes', securityDeposit: 'Security deposit', priceBreakdown: 'Price breakdown', estimatedTotal: 'Estimated initial total', invalidFeeAmount: 'Enter whole amounts of 0 FCFA or more.', bedrooms: 'Bedrooms', bathrooms: 'Bathrooms', choosePhotos: 'Choose and compress photos', photo: 'Photo {count}', untitled: 'Untitled', pricePending: 'Price pending', publishNotice: 'Final publication requires a connection. The server validates ownership, files, and data.', uploading: 'Uploading {count}%', publishProperty: 'Publish property', saveChanges: 'Save changes', saving: 'Saving…',
    personalData: 'Personal details', phone: 'Phone', address: 'Address', document: 'Document', taxInfo: 'Tax information', payoutMethod: 'Payout method', plan: 'Plan', review: 'Review', confirmation: 'Confirmation', stepOf: 'Step {current} of {total}', secureDocument: 'Sensitive documents are sent directly to the backend and are not stored in the local draft.', documentSent: 'Document sent', sendDocument: 'Send document securely',
    sendResetCode: 'Send a code to create a password', createPasswordForAccount: 'Create a password for this account', createAccountWithEmail: 'Create an account with this email', propertyImageLabel: '{title}, property photo', pushEnableFailed: 'Notifications could not be enabled', pushEnableRetry: 'Try again when the service is available.',
    pickLocationRequired: 'Select the exact location of the home to continue.', pickLocationBeforePublish: 'Select the exact location of the home before publishing.', imagesProcessError: 'The images could not be processed', publishError: 'The listing could not be published', priceTypePerMonth: 'Per month', priceTypePerNight: 'Per night', priceTypeSale: 'Sale', photoControlsUp: 'Move photo {count} up', photoControlsDown: 'Move photo {count} down', photoControlsRemove: 'Remove photo {count}',
    editPropertyNote: 'Changes are validated again on the server.', loadingListing: 'Loading listing…',
    locationDeniedTitle: 'Permission not granted', locationDeniedBody: 'You can keep exploring the map and search by location manually.', useMyLocation: 'Use my location', useMyLocationBody: 'CasaSeg will use your location once to center the map and show nearby homes. It will not be stored.', notNow: 'Not now', mapLoadError: 'Could not load. Retry', passwordTooShort: 'The password must be at least 8 characters long.', passwordsDontMatch: 'The passwords do not match.', resetExpired: 'The request expired. Ask for a new code.', resetCodeSubtitle: 'Enter the code we sent you and your new password.', verificationCode: 'Verification code', settingsSecurityNote: 'Your settings are stored securely in your account.', errorScreenTitle: 'Something went wrong', errorScreenBody: 'This screen could not be shown. Try again; if it happens again, close and reopen the app.', pickLocationHint: 'Tap the map to mark the home. You can drag the marker to adjust it.', pickLocationDone: 'Point selected for the public map', pickLocationPending: 'Select a point to continue', coordinatesHint: 'Enter the exact coordinates of the home to show it on the map.', latitude: 'Latitude', longitude: 'Longitude', latitudeLabel: 'Home latitude', longitudeLabel: 'Home longitude', coordinatesValid: 'Valid coordinates', coordinatesPending: 'Enter both coordinates to continue',
    verifyingRole: 'Checking role', roleUnavailable: 'Role unavailable', roleCheckFailed: 'We could not verify your role', roleCheckFailedBody: 'Sign out and sign back in. If it continues, an administrator needs to review the linked profile.', protectedAccount: 'Protected account', protectedAccountBody: 'Your data and conversations are handled with secure access.', professionalSpace: 'PROFESSIONAL SPACE', yourSearch: 'Your search', savedActionDetail: 'Properties you want to compare', messagesActionDetail: 'Conversations with owners', notificationsActionDetail: 'Alerts, messages and activity', settingsActionDetail: 'Theme, language and preferences', quickManagement: 'Quick management', myPropertiesActionDetail: 'Listings and drafts', contractsActionDetail: 'Documents and signatures', paymentsActionDetail: 'Payouts and transactions',
    exploreProperties: 'Explore properties', changeFilters: 'Change filters', changeSortOrder: 'Change property order', exploreLoadingTitle: 'Finding properties', exploreLoadingBody: 'We are preparing the best options for you.', exploreErrorTitle: 'We could not load the properties', exploreEmptyTitle: 'No results for these filters', loadingMoreProperties: 'Loading more properties…', availableOnly: 'Available', occupiedOnly: 'Occupied', closeGallery: 'Close gallery',
    savedEyebrow: 'YOUR COLLECTION', savedTitleFilled: 'Homes that inspire you', savedTitleEmpty: 'Your personal selection', savedDetailFilled: 'Compare your favorites and choose calmly.', savedDetailEmpty: 'Save properties to find them again quickly.', savedCount: '{count} saved', savedGuestTitle: 'Your favorites, always with you', savedGuestBody: 'Sign in to save properties, compare them and sync them across all your devices.', savedLoadingTitle: 'Preparing your collection', savedLoadingBody: 'We are syncing the properties you saved.', savedErrorTitle: 'We could not load your favorites', savedErrorBody: 'Your collection is safe. Check your connection and try again.',
    messagesEyebrow: 'SECURE CONVERSATIONS', inbox: 'Inbox', inboxDetail: 'Questions about properties, visits and contracts.', unreadCount: '{count} unread', openConversationWith: 'Open conversation with {title}', messagesGuestTitle: 'Talk directly with owners', messagesGuestBody: 'Sign in to ask questions, arrange visits and keep the history of every property.', messagesLoadingTitle: 'Opening your conversations', messagesLoadingBody: 'We are securely retrieving your messages.', messagesErrorTitle: 'We could not open your inbox', messageSent: 'Sent', messageDelivered: 'Delivered', messageRead: 'Read', messageSendError: 'The message could not be sent. Try again.',
  },
} as const;

export type TranslationKey = keyof (typeof copy)['es'];

const supportedLocales = new Set<Locale>(['es', 'fr', 'en']);

function isSupportedLocale(value: string | null): value is Locale {
  return Boolean(value && supportedLocales.has(value as Locale));
}

export function I18nProvider({ children }: PropsWithChildren) {
  const deviceLocales = useLocales();
  const deviceLocale = deviceLocales
    .map(({ languageCode }) => languageCode?.toLowerCase() ?? null)
    .find(isSupportedLocale) ?? 'es';
  const [localeOverride, setLocaleOverride] = useState<Locale | null>(() => {
    const savedLocale = appStorage.getItem('casaseg.locale');
    return isSupportedLocale(savedLocale) ? savedLocale : null;
  });
  const locale = localeOverride ?? deviceLocale;
  // El código fuera de React (errores de acceso, validación) lee este valor.
  // Es idempotente, así que puede hacerse durante el render.
  setActiveLocale(locale);
  const setLocale = useCallback((value: Locale) => {
    setLocaleOverride(value);
    appStorage.setItem('casaseg.locale', value);
  }, []);
  const value = useMemo<I18nContextValue>(
    () => ({
      locale,
      setLocale,
      t: (key, variables) => {
        let value: string = copy[locale][key];
        Object.entries(variables ?? {}).forEach(([name, replacement]) => {
          value = value.replace(`{${name}}`, replacement);
        });
        return value;
      },
    }),
    [locale, setLocale],
  );

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
