import * as Location from 'expo-location';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { ArrowLeft, List, LocateFixed, Search } from '@/components/ui/icons';
import { useRef, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FilterSheet, type FilterSheetHandle } from '@/components/filter-sheet';
import { PropertyMap } from '@/components/property-map';
import { actionGradient, colors, radius } from '@/constants/theme';
import { useAppTheme } from '@/providers/theme-context';
import { useI18n } from '@/providers/i18n-context';
import { useExplorerStore } from '@/stores/explorer-store';
import type { Property } from '@/types';
import { formatXaf } from '@/utils/formatters';

export default function MapScreen() {
  const { palette } = useAppTheme(); const { t } = useI18n(); const filterRef = useRef<FilterSheetHandle>(null); const filters = useExplorerStore((state) => state.filters); const setViewMode = useExplorerStore((state) => state.setViewMode); const [selected, setSelected] = useState<Property | null>(null); const [userLocation, setUserLocation] = useState<{ latitude: number; longitude: number } | null>(null);
  const requestLocation = () => Alert.alert('Usar mi ubicación', 'CasaSeg usará tu ubicación una sola vez para centrar el mapa y mostrar viviendas cercanas. No se guardará.', [{ text: 'Ahora no', style: 'cancel' }, { text: 'Continuar', onPress: () => void locate() }]);
  const locate = async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) { Alert.alert('Permiso no concedido', 'Puedes seguir explorando el mapa y buscar por ubicación manualmente.'); return; } const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setUserLocation({ latitude: current.coords.latitude, longitude: current.coords.longitude }); };
  const openList = () => { setViewMode('list'); router.replace('/(tabs)/explore'); };
  const goBack = () => { setViewMode('list'); router.back(); };
  return <View style={styles.container}><PropertyMap onSelect={setSelected} userLocation={userLocation} /><SafeAreaView pointerEvents="box-none" style={styles.overlay}><View style={styles.top}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel={t('back')} onPress={goBack} style={[styles.iconButton, { backgroundColor: palette.surface }]}><ArrowLeft color={palette.text} size={22} /></Pressable><Pressable accessibilityRole="button" onPress={() => filterRef.current?.present()} style={[styles.search, { backgroundColor: palette.surface }]}><Search color={palette.textSecondary} size={20} /><Text numberOfLines={1} style={[styles.searchText, { color: palette.text }]}>{filters.location || t('mapSearch')}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={t('viewList')} onPress={openList} style={styles.viewToggle}><LinearGradient colors={actionGradient} style={styles.viewToggleGradient}><List color="white" size={21} /></LinearGradient></Pressable></View><View style={[styles.count, { backgroundColor: palette.surface }]}><Text style={[styles.countText, { color: palette.text }]}>3 {t('properties')}</Text></View></View><View style={styles.bottom}><View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel={t('myLocation')} onPress={requestLocation} style={[styles.iconButton, { backgroundColor: palette.surface }]}><LocateFixed color={colors.primary} size={22} /></Pressable></View>{selected && <Pressable onPress={() => router.push({ pathname: '/property/[id]', params: { id: selected.id } })} style={[styles.selected, { backgroundColor: palette.surface }]}><Image source={{ uri: selected.imageUrls[0] }} cachePolicy="disk" contentFit="cover" style={styles.thumb} /><View style={styles.selectedCopy}><Text numberOfLines={1} style={[styles.selectedTitle, { color: palette.text }]}>{selected.title}</Text><Text style={[styles.selectedLocation, { color: palette.textSecondary }]}>{selected.location}</Text><Text style={[styles.selectedPrice, { color: colors.brandDark }]}>{formatXaf(selected.price)}</Text></View></Pressable>}</View></SafeAreaView><FilterSheet ref={filterRef} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1 }, overlay: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, justifyContent: 'space-between' }, top: { gap: 10 }, header: { paddingHorizontal: 16, flexDirection: 'row', gap: 8, alignItems: 'center' }, iconButton: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' }, search: { flex: 1, minHeight: 50, borderRadius: radius.pill, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 10 }, searchText: { flex: 1, fontSize: 15, fontWeight: '800' }, viewToggle: { borderRadius: 25, height: 50, overflow: 'hidden', width: 50 }, viewToggleGradient: { alignItems: 'center', flex: 1, justifyContent: 'center' }, count: { alignSelf: 'center', borderRadius: radius.pill, paddingHorizontal: 14, paddingVertical: 8 }, countText: { fontSize: 13, fontWeight: '800' }, bottom: { padding: 16, gap: 10 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center' }, selected: { minHeight: 104, borderRadius: radius.lg, padding: 10, flexDirection: 'row', gap: 12 }, thumb: { width: 108, borderRadius: radius.md }, selectedCopy: { flex: 1, justifyContent: 'center', gap: 4 }, selectedTitle: { fontSize: 15, fontWeight: '900' }, selectedLocation: { fontSize: 13 }, selectedPrice: { fontSize: 15, fontWeight: '900' } });
