import { useQuery } from '@tanstack/react-query';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { router, useLocalSearchParams, type Href } from 'expo-router';
import { ArrowLeft, Bath, BedDouble, CheckCircle2, Heart, MapPin, Maximize2, ShieldCheck, Star, UserRound } from '@/components/ui/icons';
import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { PropertyGallery } from '@/components/property/property-gallery';
import { PropertyMap } from '@/components/property-map';
import { brandGradient, colors, radius } from '@/constants/theme';
import { propertyKeys } from '@/features/properties/api/property.keys';
import { fetchFavorites } from '@/features/properties/api/property.queries';
import { useFavoriteMutation } from '@/features/properties/hooks/use-favorite-mutation';
import { useProperty } from '@/features/properties/hooks/use-properties';
import { useAuth } from '@/providers/auth-context';
import { useAppTheme } from '@/providers/theme-context';
import { useI18n } from '@/providers/i18n-context';
import { formatXaf } from '@/utils/formatters';

export default function PropertyDetailScreen() {
  const { id, conversationId } = useLocalSearchParams<{ id: string; conversationId?: string }>();
  const { palette } = useAppTheme(); const { t, locale } = useI18n(); const insets = useSafeAreaInsets(); const { user, isAuthenticated } = useAuth();
  const propertyQuery = useProperty(id); const property = propertyQuery.data; const [galleryVisible, setGalleryVisible] = useState(false); const [guestFavorite, setGuestFavorite] = useState(false);
  const favorites = useQuery({ queryKey: propertyKeys.favorites(user?.id ?? 'guest'), queryFn: () => fetchFavorites(user!.id), enabled: Boolean(user) });
  const favoriteMutation = useFavoriteMutation(user?.id ?? 'guest');
  if (propertyQuery.isLoading) return <View style={[styles.center, { backgroundColor: palette.background }]}><ActivityIndicator color={colors.brand} size="large" /></View>;
  if (!property) return <View style={[styles.center, { backgroundColor: palette.background }]}><Text style={{ color: palette.text }}>{t('notFound')}</Text></View>;
  const isFavorite = isAuthenticated ? favorites.data?.includes(property.id) ?? false : guestFavorite;
  const isOwnProperty = user?.id === property.ownerId;
  const cta = isOwnProperty ? t('editProperty') : conversationId ? t('openConversation') : !isAuthenticated ? t('loginToContact') : property.isOccupied ? t('waitingList') : t('contact');
  const onCta = () => { if (!isAuthenticated) router.push('/(auth)/login'); else if (isOwnProperty) router.push({ pathname: '/owner/property/[id]', params: { id: property.id } }); else router.push({ pathname: '/chat/[conversationId]', params: { conversationId: conversationId ?? `property-${property.id}` } }); };
  const toggleFavorite = () => { const next = !isFavorite; if (!isAuthenticated) setGuestFavorite(next); else favoriteMutation.mutate({ propertyId: property.id, favorite: next }); };
  return <View style={[styles.screen, { backgroundColor: palette.background }]}>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
      <Pressable accessibilityRole="button" onPress={() => setGalleryVisible(true)} style={styles.galleryButton}><Image source={{ uri: property.imageUrls[0] }} placeholder={{ blurhash: 'LEHV6nWB2yk8pyo0adR*.7kCMdnj' }} cachePolicy="disk" contentFit="cover" transition={180} style={styles.heroImage} /><LinearGradient colors={['rgba(15,23,42,0.28)', 'transparent']} style={styles.heroShade} /><Text style={styles.imageCounter}>1 / {property.imageUrls.length}</Text></Pressable>
      <SafeAreaView edges={['top']} style={styles.topActions}><Pressable accessibilityRole="button" accessibilityLabel={t('back')} onPress={() => router.back()} style={styles.circle}><ArrowLeft color={colors.text} size={23} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel={isFavorite ? t('removeFavorite') : t('saveProperty')} onPress={toggleFavorite} style={styles.circle}><Heart color={isFavorite ? colors.favorite : colors.text} fill={isFavorite ? colors.favorite : 'transparent'} size={23} /></Pressable></SafeAreaView>
      <View style={styles.content}><View style={styles.titleRow}><Text style={[styles.title, { color: palette.text }]}>{property.title}</Text><View style={styles.rating}><Star color={colors.warning} fill={colors.warning} size={18} /><Text style={[styles.ratingText, { color: palette.text }]}>{property.rating.toFixed(1)}</Text></View></View><View style={styles.inline}><MapPin color={palette.textSecondary} size={18} /><Text style={[styles.body, { color: palette.textSecondary }]}>{property.location}</Text></View><Text style={[styles.price, { color: palette.text }]}>{formatXaf(property.price, property.priceType, locale === 'fr' ? 'fr-FR' : locale === 'en' ? 'en-US' : 'es-GQ')}</Text>
        <View style={[styles.features, { backgroundColor: palette.surface }]}><Feature icon={<BedDouble color={colors.brandDark} size={21} />} value={t('beds', { count: String(property.bedrooms) })} color={palette.text} /><Feature icon={<Bath color={colors.brandDark} size={21} />} value={t('baths', { count: String(property.bathrooms) })} color={palette.text} /><Feature icon={<Maximize2 color={colors.brandDark} size={20} />} value={`${property.area} m²`} color={palette.text} /></View>
        <Section title={t('description')} color={palette.text}><Text style={[styles.body, { color: palette.textSecondary }]}>{property.description}</Text></Section>
        <Section title={t('amenities')} color={palette.text}><View style={styles.chips}>{property.amenities.map((amenity) => <View key={amenity} style={[styles.chip, { backgroundColor: palette.surface }]}><CheckCircle2 color={colors.success} size={16} /><Text style={{ color: palette.textSecondary, fontWeight: '700' }}>{amenity}</Text></View>)}</View></Section>
        <Section title={t('owner')} color={palette.text}><View style={[styles.owner, { backgroundColor: palette.surface }]}><View style={styles.avatar}><UserRound color="white" size={24} /></View><View style={styles.flex}><Text style={[styles.ownerName, { color: palette.text }]}>{property.ownerName}</Text><Text style={[styles.caption, { color: palette.textSecondary }]}>{t('verifiedIdentity')}</Text></View><ShieldCheck color={colors.success} size={24} /></View></Section>
        <Section title={t('location')} color={palette.text}><Pressable accessibilityRole="button" onPress={() => router.push('/map')} style={styles.mapFrame}><PropertyMap /></Pressable></Section>
        {isAuthenticated && !isOwnProperty && <Pressable onPress={() => router.push({ pathname: '/visit/[propertyId]', params: { propertyId: property.id } } as unknown as Href)} style={[styles.visitButton, { borderColor: palette.border }]}><Text style={{ color: palette.text, fontWeight: '900' }}>{t('requestVisit')}</Text></Pressable>}
        <View style={[styles.legal, { backgroundColor: palette.surface }]}><ShieldCheck color={property.legalStatus === 'verified' ? colors.success : colors.warning} size={23} /><View><Text style={[styles.ownerName, { color: palette.text }]}>{property.legalStatus === 'verified' ? t('documentVerified') : t('verificationPending')}</Text><Text style={[styles.caption, { color: palette.textSecondary }]}>{property.isOccupied ? t('occupied') : t('available')}</Text></View></View>
      </View>
      <View style={{ height: insets.bottom }} />
    </ScrollView>
    <View style={[styles.ctaBar, { paddingBottom: Math.max(insets.bottom, 12), backgroundColor: palette.surface, borderColor: palette.border }]}><Pressable accessibilityRole="button" onPress={onCta}><LinearGradient colors={brandGradient} style={styles.cta}><Text style={styles.ctaText}>{cta}</Text></LinearGradient></Pressable></View>
    <PropertyGallery visible={galleryVisible} images={property.imageUrls} title={property.title} onClose={() => setGalleryVisible(false)} />
  </View>;
}
function Feature({ icon, value, color }: { icon: React.ReactNode; value: string; color: string }) { return <View style={styles.feature}>{icon}<Text style={{ color, fontWeight: '800' }}>{value}</Text></View>; }
function Section({ title, color, children }: { title: string; color: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={[styles.sectionTitle, { color }]}>{title}</Text>{children}</View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, scrollContent: { paddingBottom: 104 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, galleryButton: { width: '100%', aspectRatio: 4 / 3, backgroundColor: colors.subtle }, heroImage: { flex: 1 }, heroShade: { position: 'absolute', top: 0, left: 0, right: 0, height: 120 }, imageCounter: { position: 'absolute', right: 16, bottom: 16, color: 'white', backgroundColor: 'rgba(15,23,42,.64)', paddingHorizontal: 12, paddingVertical: 7, borderRadius: radius.pill, fontWeight: '800' }, topActions: { position: 'absolute', left: 16, right: 16, top: 0, flexDirection: 'row', justifyContent: 'space-between' }, circle: { width: 48, height: 48, borderRadius: 24, backgroundColor: 'rgba(255,255,255,.95)', alignItems: 'center', justifyContent: 'center' }, content: { padding: 20, gap: 20 }, titleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 }, title: { flex: 1, fontSize: 27, lineHeight: 33, fontWeight: '900' }, rating: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingTop: 6 }, ratingText: { fontWeight: '800' }, inline: { flexDirection: 'row', alignItems: 'center', gap: 7 }, body: { flex: 1, fontSize: 15, lineHeight: 23 }, price: { fontSize: 21, fontWeight: '900' }, features: { flexDirection: 'row', borderRadius: radius.lg, padding: 16, justifyContent: 'space-between' }, feature: { alignItems: 'center', gap: 7 }, section: { gap: 10 }, sectionTitle: { fontSize: 22, fontWeight: '900' }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { minHeight: 40, borderRadius: radius.pill, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 7 }, owner: { minHeight: 76, borderRadius: radius.lg, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, ownerName: { fontSize: 15, fontWeight: '800' }, caption: { fontSize: 13, marginTop: 3 }, mapFrame: { height: 180, borderRadius: radius.lg, overflow: 'hidden' }, visitButton: { minHeight: 52, borderRadius: radius.md, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, legal: { minHeight: 72, borderRadius: radius.lg, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12 }, ctaBar: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopWidth: StyleSheet.hairlineWidth, paddingHorizontal: 16, paddingTop: 12 }, cta: { minHeight: 56, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, ctaText: { color: 'white', fontSize: 16, fontWeight: '900' } });
