import { HugeiconsIcon, type HugeiconsProps, type IconSvgElement } from '@hugeicons/react-native';
import { createElement } from 'react';
import Add01Icon from '@hugeicons/core-free-icons/Add01Icon';
import AlertCircleIcon from '@hugeicons/core-free-icons/AlertCircleIcon';
import AppleIcon from '@hugeicons/core-free-icons/AppleIcon';
import ArrowDown01Icon from '@hugeicons/core-free-icons/ArrowDown01Icon';
import ArrowDown02Icon from '@hugeicons/core-free-icons/ArrowDown02Icon';
import ArrowLeft02Icon from '@hugeicons/core-free-icons/ArrowLeft02Icon';
import ArrowRight01Icon from '@hugeicons/core-free-icons/ArrowRight01Icon';
import ArrowRight02Icon from '@hugeicons/core-free-icons/ArrowRight02Icon';
import ArrowUp01Icon from '@hugeicons/core-free-icons/ArrowUp01Icon';
import ArrowUp02Icon from '@hugeicons/core-free-icons/ArrowUp02Icon';
import ArrowUpRight01Icon from '@hugeicons/core-free-icons/ArrowUpRight01Icon';
import Bathtub01Icon from '@hugeicons/core-free-icons/Bathtub01Icon';
import BedDoubleIcon from '@hugeicons/core-free-icons/BedDoubleIcon';
import Building03Icon from '@hugeicons/core-free-icons/Building03Icon';
import Calendar03Icon from '@hugeicons/core-free-icons/Calendar03Icon';
import Call02Icon from '@hugeicons/core-free-icons/Call02Icon';
import Camera01Icon from '@hugeicons/core-free-icons/Camera01Icon';
import Cancel01Icon from '@hugeicons/core-free-icons/Cancel01Icon';
import CancelCircleIcon from '@hugeicons/core-free-icons/CancelCircleIcon';
import CarParking01Icon from '@hugeicons/core-free-icons/CarParking01Icon';
import ChartLineData01Icon from '@hugeicons/core-free-icons/ChartLineData01Icon';
import CheckmarkBadge01Icon from '@hugeicons/core-free-icons/CheckmarkBadge01Icon';
import CheckmarkCircle02Icon from '@hugeicons/core-free-icons/CheckmarkCircle02Icon';
import Clock01Icon from '@hugeicons/core-free-icons/Clock01Icon';
import Navigation05Icon from '@hugeicons/core-free-icons/Navigation05Icon';
import ComputerIcon from '@hugeicons/core-free-icons/ComputerIcon';
import CreditCardIcon from '@hugeicons/core-free-icons/CreditCardIcon';
import CrownIcon from '@hugeicons/core-free-icons/CrownIcon';
import Delete02Icon from '@hugeicons/core-free-icons/Delete02Icon';
import DoorIcon from '@hugeicons/core-free-icons/DoorIcon';
import FavouriteIcon from '@hugeicons/core-free-icons/FavouriteIcon';
import File02Icon from '@hugeicons/core-free-icons/File02Icon';
import FlashIcon from '@hugeicons/core-free-icons/FlashIcon';
import GridViewIcon from '@hugeicons/core-free-icons/GridViewIcon';
import HelpCircleIcon from '@hugeicons/core-free-icons/HelpCircleIcon';
import Home01Icon from '@hugeicons/core-free-icons/Home01Icon';
import Home02Icon from '@hugeicons/core-free-icons/Home02Icon';
import Home11Icon from '@hugeicons/core-free-icons/Home11Icon';
import ImageAdd01Icon from '@hugeicons/core-free-icons/ImageAdd01Icon';
import InboxIcon from '@hugeicons/core-free-icons/InboxIcon';
import InformationCircleIcon from '@hugeicons/core-free-icons/InformationCircleIcon';
import Key01Icon from '@hugeicons/core-free-icons/Key01Icon';
import Layers01Icon from '@hugeicons/core-free-icons/Layers01Icon';
import LeftToRightListBulletIcon from '@hugeicons/core-free-icons/LeftToRightListBulletIcon';
import LinkSquare02Icon from '@hugeicons/core-free-icons/LinkSquare02Icon';
import Location01Icon from '@hugeicons/core-free-icons/Location01Icon';
import LocationCheck01Icon from '@hugeicons/core-free-icons/LocationCheck01Icon';
import LockIcon from '@hugeicons/core-free-icons/LockIcon';
import Login01Icon from '@hugeicons/core-free-icons/Login01Icon';
import Logout01Icon from '@hugeicons/core-free-icons/Logout01Icon';
import Mail01Icon from '@hugeicons/core-free-icons/Mail01Icon';
import MapsIcon from '@hugeicons/core-free-icons/MapsIcon';
import Maximize01Icon from '@hugeicons/core-free-icons/Maximize01Icon';
import Menu01Icon from '@hugeicons/core-free-icons/Menu01Icon';
import Message01Icon from '@hugeicons/core-free-icons/Message01Icon';
import Message02Icon from '@hugeicons/core-free-icons/Message02Icon';
import Moon02Icon from '@hugeicons/core-free-icons/Moon02Icon';
import Notification01Icon from '@hugeicons/core-free-icons/Notification01Icon';
import Refresh01Icon from '@hugeicons/core-free-icons/Refresh01Icon';
import RulerIcon from '@hugeicons/core-free-icons/RulerIcon';
import Search01Icon from '@hugeicons/core-free-icons/Search01Icon';
import SecurityCheckIcon from '@hugeicons/core-free-icons/SecurityCheckIcon';
import SentIcon from '@hugeicons/core-free-icons/SentIcon';
import Settings01Icon from '@hugeicons/core-free-icons/Settings01Icon';
import Share08Icon from '@hugeicons/core-free-icons/Share08Icon';
import SlidersHorizontalIcon from '@hugeicons/core-free-icons/SlidersHorizontalIcon';
import Sofa01Icon from '@hugeicons/core-free-icons/Sofa01Icon';
import SparklesIcon from '@hugeicons/core-free-icons/SparklesIcon';
import StarIcon from '@hugeicons/core-free-icons/StarIcon';
import Sun03Icon from '@hugeicons/core-free-icons/Sun03Icon';
import SwimmingIcon from '@hugeicons/core-free-icons/SwimmingIcon';
import Target02Icon from '@hugeicons/core-free-icons/Target02Icon';
import Tick02Icon from '@hugeicons/core-free-icons/Tick02Icon';
import TickDouble02Icon from '@hugeicons/core-free-icons/TickDouble02Icon';
import TradeUpIcon from '@hugeicons/core-free-icons/TradeUpIcon';
import TranslateIcon from '@hugeicons/core-free-icons/TranslateIcon';
import Tree02Icon from '@hugeicons/core-free-icons/Tree02Icon';
import UserCircleIcon from '@hugeicons/core-free-icons/UserCircleIcon';
import UserGroupIcon from '@hugeicons/core-free-icons/UserGroupIcon';
import ViewIcon from '@hugeicons/core-free-icons/ViewIcon';
import ViewOffSlashIcon from '@hugeicons/core-free-icons/ViewOffSlashIcon';
import Wallet01Icon from '@hugeicons/core-free-icons/Wallet01Icon';
import Wifi01Icon from '@hugeicons/core-free-icons/Wifi01Icon';
import WindIcon from '@hugeicons/core-free-icons/WindIcon';

export type IconProps = Omit<HugeiconsProps, 'icon' | 'altIcon' | 'showAlt'> & {
  /** Relleno del trazo cerrado (corazón, estrella…); 'none' y 'transparent' lo dejan en contorno. */
  fill?: string;
  /** Permite mantener el contorno aunque se proporcione un color de relleno. */
  filled?: boolean;
};

export type AppIcon = (props: IconProps) => ReturnType<typeof createElement>;

// La misma familia Hugeicons se usa en Android, iOS y web.
function createIcon(icon: IconSvgElement, displayName: string): AppIcon {
  function ProjectIcon({ fill, filled, ...props }: IconProps) {
    const isFilled = filled ?? Boolean(fill && fill !== 'none' && fill !== 'transparent');
    return createElement(HugeiconsIcon, { ...props, icon, ...(isFilled ? { fill } : null) });
  }

  ProjectIcon.displayName = `CasaSegIcon(${displayName})`;
  return ProjectIcon;
}

export const AlertCircle = createIcon(AlertCircleIcon, 'AlertCircle');
export const Apple = createIcon(AppleIcon, 'Apple');
export const ArrowDown = createIcon(ArrowDown02Icon, 'ArrowDown');
export const ArrowLeft = createIcon(ArrowLeft02Icon, 'ArrowLeft');
export const ArrowRight = createIcon(ArrowRight02Icon, 'ArrowRight');
export const ArrowUp = createIcon(ArrowUp02Icon, 'ArrowUp');
export const ArrowUpRight = createIcon(ArrowUpRight01Icon, 'ArrowUpRight');
export const Bath = createIcon(Bathtub01Icon, 'Bath');
export const BedDouble = createIcon(BedDoubleIcon, 'BedDouble');
export const Bell = createIcon(Notification01Icon, 'Bell');
export const Building2 = createIcon(Building03Icon, 'Building2');
export const Calendar = createIcon(Calendar03Icon, 'Calendar');
export const Camera = createIcon(Camera01Icon, 'Camera');
export const Car = createIcon(CarParking01Icon, 'Car');
export const ChartLine = createIcon(ChartLineData01Icon, 'ChartLine');
export const Check = createIcon(Tick02Icon, 'Check');
export const CheckDouble = createIcon(TickDouble02Icon, 'CheckDouble');
export const CheckCircle2 = createIcon(CheckmarkCircle02Icon, 'CheckCircle2');
export const ChevronDown = createIcon(ArrowDown01Icon, 'ChevronDown');
export const ChevronRight = createIcon(ArrowRight01Icon, 'ChevronRight');
export const ChevronUp = createIcon(ArrowUp01Icon, 'ChevronUp');
export const Clock = createIcon(Clock01Icon, 'Clock');
export const Navigation = createIcon(Navigation05Icon, 'Navigation');
export const CreditCard = createIcon(CreditCardIcon, 'CreditCard');
export const Crown = createIcon(CrownIcon, 'Crown');
export const Door = createIcon(DoorIcon, 'Door');
export const ExternalLink = createIcon(LinkSquare02Icon, 'ExternalLink');
export const Eye = createIcon(ViewIcon, 'Eye');
export const EyeOff = createIcon(ViewOffSlashIcon, 'EyeOff');
export const FileText = createIcon(File02Icon, 'FileText');
export const Grid2X2 = createIcon(GridViewIcon, 'Grid2X2');
export const Heart = createIcon(FavouriteIcon, 'Heart');
export const HelpCircle = createIcon(HelpCircleIcon, 'HelpCircle');
export const Home = createIcon(Home01Icon, 'Home');
export const HomeTab = createIcon(Home02Icon, 'HomeTab');
export const HomeCheck = createIcon(Home11Icon, 'HomeCheck');
export const ImagePlus = createIcon(ImageAdd01Icon, 'ImagePlus');
export const Inbox = createIcon(InboxIcon, 'Inbox');
export const Info = createIcon(InformationCircleIcon, 'Info');
export const KeyRound = createIcon(Key01Icon, 'KeyRound');
export const Layers3 = createIcon(Layers01Icon, 'Layers3');
export const List = createIcon(LeftToRightListBulletIcon, 'List');
export const LocateFixed = createIcon(Target02Icon, 'LocateFixed');
export const Lock = createIcon(LockIcon, 'Lock');
export const LogIn = createIcon(Login01Icon, 'LogIn');
export const LogOut = createIcon(Logout01Icon, 'LogOut');
export const Mail = createIcon(Mail01Icon, 'Mail');
export const Map = createIcon(MapsIcon, 'Map');
export const MapPin = createIcon(Location01Icon, 'MapPin');
export const MapPinned = createIcon(LocationCheck01Icon, 'MapPinned');
export const Maximize2 = createIcon(Maximize01Icon, 'Maximize2');
export const Menu = createIcon(Menu01Icon, 'Menu');
export const MessageCircle = createIcon(Message01Icon, 'MessageCircle');
export const MessagesSquare = createIcon(Message02Icon, 'MessagesSquare');
export const Monitor = createIcon(ComputerIcon, 'Monitor');
export const Moon = createIcon(Moon02Icon, 'Moon');
export const Phone = createIcon(Call02Icon, 'Phone');
export const Plus = createIcon(Add01Icon, 'Plus');
export const RefreshCw = createIcon(Refresh01Icon, 'RefreshCw');
export const Ruler = createIcon(RulerIcon, 'Ruler');
export const Search = createIcon(Search01Icon, 'Search');
export const Send = createIcon(SentIcon, 'Send');
export const Settings = createIcon(Settings01Icon, 'Settings');
export const Share2 = createIcon(Share08Icon, 'Share2');
export const ShieldCheck = createIcon(SecurityCheckIcon, 'ShieldCheck');
export const SlidersHorizontal = createIcon(SlidersHorizontalIcon, 'SlidersHorizontal');
export const Sofa = createIcon(Sofa01Icon, 'Sofa');
export const Sparkles = createIcon(SparklesIcon, 'Sparkles');
export const Star = createIcon(StarIcon, 'Star');
export const Sun = createIcon(Sun03Icon, 'Sun');
export const Swimming = createIcon(SwimmingIcon, 'Swimming');
export const Translate = createIcon(TranslateIcon, 'Translate');
export const Trash2 = createIcon(Delete02Icon, 'Trash2');
export const Tree = createIcon(Tree02Icon, 'Tree');
export const TrendingUp = createIcon(TradeUpIcon, 'TrendingUp');
export const UserRound = createIcon(UserCircleIcon, 'UserRound');
export const UsersRound = createIcon(UserGroupIcon, 'UsersRound');
export const Verified = createIcon(CheckmarkBadge01Icon, 'Verified');
export const Wallet = createIcon(Wallet01Icon, 'Wallet');
export const Wifi = createIcon(Wifi01Icon, 'Wifi');
export const Wind = createIcon(WindIcon, 'Wind');
export const X = createIcon(Cancel01Icon, 'X');
export const XCircle = createIcon(CancelCircleIcon, 'XCircle');
export const Zap = createIcon(FlashIcon, 'Zap');
