import type MaterialIcons from '@expo/vector-icons/MaterialIcons';
import type { ComponentProps } from 'react';

type MaterialName = ComponentProps<typeof MaterialIcons>['name'];
type MaterialGlyph = { outline: MaterialName; filled?: MaterialName };

// One Material counterpart for every shared app icon. Native tabs use md.
export const materialIconMap = {
  AlertCircle: { outline: 'error-outline', filled: 'error' },
  Apple: { outline: 'apple' },
  ArrowDown: { outline: 'arrow-downward' },
  ArrowLeft: { outline: 'arrow-back' },
  ArrowRight: { outline: 'arrow-forward' },
  ArrowUp: { outline: 'arrow-upward' },
  ArrowUpRight: { outline: 'north-east' },
  Bath: { outline: 'bathtub' },
  BedDouble: { outline: 'bed' },
  Bell: { outline: 'notifications-none', filled: 'notifications' },
  Building2: { outline: 'apartment' },
  Calendar: { outline: 'calendar-today' },
  Camera: { outline: 'photo-camera' },
  Car: { outline: 'local-parking' },
  ChartLine: { outline: 'show-chart' },
  Check: { outline: 'check' },
  CheckDouble: { outline: 'done-all' },
  CheckCircle2: { outline: 'check-circle-outline', filled: 'check-circle' },
  ChevronDown: { outline: 'expand-more' },
  ChevronRight: { outline: 'chevron-right' },
  ChevronUp: { outline: 'expand-less' },
  Clock: { outline: 'schedule' },
  Compass: { outline: 'explore' },
  CreditCard: { outline: 'credit-card' },
  Crown: { outline: 'workspace-premium' },
  Door: { outline: 'door-front' },
  ExternalLink: { outline: 'open-in-new' },
  Eye: { outline: 'visibility' },
  EyeOff: { outline: 'visibility-off' },
  FileText: { outline: 'description' },
  Grid2X2: { outline: 'grid-view' },
  Heart: { outline: 'favorite-border', filled: 'favorite' },
  HelpCircle: { outline: 'help-outline', filled: 'help' },
  Home: { outline: 'home' },
  HomeTab: { outline: 'home' },
  HomeCheck: { outline: 'home-work' },
  ImagePlus: { outline: 'add-photo-alternate' },
  Inbox: { outline: 'inbox' },
  Info: { outline: 'info-outline', filled: 'info' },
  KeyRound: { outline: 'vpn-key' },
  Layers3: { outline: 'layers' },
  List: { outline: 'format-list-bulleted' },
  LocateFixed: { outline: 'my-location' },
  Lock: { outline: 'lock-outline', filled: 'lock' },
  LogIn: { outline: 'login' },
  LogOut: { outline: 'logout' },
  Mail: { outline: 'mail-outline', filled: 'mail' },
  Map: { outline: 'map' },
  MapPin: { outline: 'location-on' },
  MapPinned: { outline: 'where-to-vote' },
  Maximize2: { outline: 'fullscreen' },
  Menu: { outline: 'menu' },
  MessageCircle: { outline: 'chat-bubble-outline', filled: 'chat-bubble' },
  MessagesSquare: { outline: 'forum' },
  Monitor: { outline: 'desktop-windows' },
  Moon: { outline: 'dark-mode' },
  Phone: { outline: 'phone' },
  Plus: { outline: 'add' },
  RefreshCw: { outline: 'refresh' },
  Ruler: { outline: 'straighten' },
  Search: { outline: 'search' },
  Send: { outline: 'send' },
  Settings: { outline: 'settings' },
  Share2: { outline: 'share' },
  ShieldCheck: { outline: 'verified-user' },
  SlidersHorizontal: { outline: 'tune' },
  Sofa: { outline: 'weekend' },
  Sparkles: { outline: 'auto-awesome' },
  Star: { outline: 'star-border', filled: 'star' },
  Sun: { outline: 'light-mode' },
  Swimming: { outline: 'pool' },
  Translate: { outline: 'translate' },
  Trash2: { outline: 'delete-outline', filled: 'delete' },
  Tree: { outline: 'park' },
  TrendingUp: { outline: 'trending-up' },
  UserRound: { outline: 'account-circle' },
  UsersRound: { outline: 'groups' },
  Verified: { outline: 'verified' },
  Wallet: { outline: 'account-balance-wallet' },
  Wifi: { outline: 'wifi' },
  Wind: { outline: 'air' },
  X: { outline: 'close' },
  XCircle: { outline: 'cancel' },
  Zap: { outline: 'flash-on' },
} satisfies Record<string, MaterialGlyph>;

export type AppIconName = keyof typeof materialIconMap;

export function materialIconName(name: AppIconName, filled: boolean): MaterialName {
  const glyph: MaterialGlyph = materialIconMap[name];
  return filled ? glyph.filled ?? glyph.outline : glyph.outline;
}
